#!/usr/bin/env node
const stompit = require('stompit')
const argv = require('yargs')
  .usage(
    `Usage: <filename> -q "/test/test" -m 'message' -h localhost 
    
    -h    [host/ip] 
    -q    [queue] 
    -m    [message] 
    -p    [port| default: 61613] 
    -u    [user] 
    -t    [type]
    -pass [password]`
  )
  .demandOption(['q', 'm', 'h']).argv

console.log(argv)

stompit.connect(
  {
    host: argv.h,
    port: argv.p || 61613,
    connectHeaders: {
      'heart-beat': '1000,2000',
      host: argv.h,
      login: argv.u,
      passcode: argv.pass
    }
  },
  (err, client) => {
    const frame = client.send({ destination: argv.q, messageType: argv.t })

    frame.write(typeof argv.m === 'string' ? argv.m : JSON.stringify(argv.m))
    frame.end()
    client.disconnect()
    console.log(' 📧  message sent !')
  }
)
